#!/usr/bin/env bash
# Bash script that creates an RSA key pair
#ssh-keygen -b 4096 -P betty -f alx-system_engineering-devops/0x0B-ssh/school
ssh-keygen -t rsa -b 4096 -P betty -f alx-system_engineering-devops/0x0B-ssh/school
